
import Foundation

enum AceQuestionBank {
    static let all: [AceQuestion] = [
        // Experimental chemistry
        q("exp_p1",.experimental,.planning,2,"Plan a method to separate a mixture of sand and soluble sodium chloride and obtain dry sodium chloride.","Add water to dissolve sodium chloride; filter to remove sand; evaporate some water and crystallise the sodium chloride; filter crystals and dry them.","Saying 'filter the mixture' alone does not separate dissolved salt.","Name each separation step and explain which property makes it work."),
        q("exp_m1",.experimental,.mmo,2,"Why should the bottom of the meniscus be read at eye level for a colourless aqueous solution?","To reduce parallax error and obtain a more accurate volume reading.","Reading from above or below eye level without explaining parallax.","State both the action and the error it prevents."),
        q("exp_a1",.experimental,.ace,2,"A chromatography spot travels 3.2 cm while the solvent front travels 8.0 cm. Calculate Rf.","Rf = 3.2/8.0 = 0.40.","Multiplying the two distances.","Rf is a ratio and has no unit."),

        // Particulate nature
        q("part_p1",.particulate,.planning,2,"Describe how you could obtain evidence that particles in a gas are in constant random motion.","Observe diffusion of a gas into another gas, or a suitable smoke-particle experiment, and describe the spreading without stirring.","Saying only that particles 'move'.","Link the visible observation to random particle motion."),
        q("part_a1",.particulate,.ace,2,"Explain why diffusion is faster at higher temperature.","Particles have greater average kinetic energy and move faster, so mixing occurs more rapidly.","Saying particles become larger or there are more particles.","Use kinetic energy and particle speed."),

        // Bonding
        q("bond_a1",.bonding,.ace,3,"Explain why molten ionic compounds conduct electricity but solid ionic compounds do not.","In the solid, ions are held in fixed positions. When molten, ions are free to move and carry charge.","Saying electrons flow in an ionic compound.","Identify the charge carriers as ions."),
        q("bond_p1",.bonding,.pdo,2,"A student is given melting-point data for several substances. What evidence could support a conclusion that a substance has a giant structure?","A very high melting point compared with simple molecular substances, consistent with many strong bonds requiring substantial energy to overcome.","High melting point alone proves the structure.","Use data as supporting evidence, not as an absolute identification."),

        // Calculations
        q("calc_p1",.calculations,.planning,3,"Plan how to determine the concentration of an acid using titration against a solution of known concentration.","Pipette a fixed volume of the known solution into a conical flask; add indicator; titrate with the acid from a burette; repeat until concordant titres are obtained; use the balanced equation and mole ratios to calculate concentration.","Using a measuring cylinder for the fixed aliquot when a pipette is available.","Include repeat titrations and concordance."),
        q("calc_ace1",.calculations,.ace,3,"25.0 cm³ of 0.100 mol/dm³ NaOH reacts exactly with 20.0 cm³ HCl. Find the HCl concentration.","NaOH + HCl → NaCl + H₂O. Moles NaOH = 0.0250×0.100 = 0.00250 mol. Ratio 1:1, so HCl = 0.00250 mol. Concentration = 0.00250/0.0200 = 0.125 mol/dm³.","Forgetting to convert cm³ to dm³ or using the wrong mole ratio.","Show the balanced equation before the calculation."),
        q("calc_pdo1",.calculations,.pdo,2,"A balance reads 2.50 g for a sample. How should the result be recorded if the balance displays to 0.01 g?","2.50 g, retaining the displayed precision.","Writing 2.5 g and losing a decimal place.","Do not discard justified trailing zeros."),

        // Acid-base
        q("acid_p1",.acidBase,.planning,3,"Describe a safe experiment to compare the pH of two aqueous solutions.","Use equal-sized samples; test each with Universal Indicator or a pH probe; record the colour/pH using the same method and compare.","Using taste or directly mixing unknown chemicals.","Use small samples and appropriate indicators/apparatus."),
        q("acid_m1",.acidBase,.mmo,2,"In a titration, why is the indicator added in small quantity?","It should signal the end-point without significantly changing the volume or composition of the reaction mixture.","Because indicators are dangerous in all cases.","The indicator is not the reactant being measured."),
        q("acid_ace1",.acidBase,.ace,2,"Explain why a strong acid has a lower pH than a weak acid of the same concentration.","A strong acid ionises more extensively, producing a higher concentration of H⁺ ions.","Saying strong acids contain 'more acid particles' without referring to ionisation.","Compare the extent of ionisation and H⁺ concentration."),

        // Qualitative
        q("qual_p1",.qualitative,.planning,3,"An unknown solution may contain chloride ions. State a suitable test and observation.","Acidify with dilute nitric acid, then add aqueous silver nitrate. A white precipitate indicates chloride ions.","Using hydrochloric acid to acidify introduces chloride ions.","Use nitric acid so chloride is not introduced."),
        q("qual_m1",.qualitative,.mmo,3,"Describe the test for carbonate ions.","Add dilute acid. Effervescence occurs; the gas produced turns limewater milky.","Saying only 'bubbles form' without identifying or testing the gas.","Include the gas test for carbon dioxide."),
        q("qual_ace1",.qualitative,.ace,3,"A solution gives a white precipitate with aqueous sodium hydroxide, soluble in excess sodium hydroxide. What conclusion may be drawn at O-Level?","The cation may be aluminium(III) or zinc(II); use the specified confirmatory tests in the Notes for Qualitative Analysis to distinguish them.","Claiming a single ion without a confirmatory test.","Do not over-identify when the observation is shared by more than one ion."),

        // Redox
        q("redox_ace1",.redox,.ace,2,"Define oxidation and reduction in terms of electron transfer.","Oxidation is loss of electrons; reduction is gain of electrons.","Reversing the two definitions.","Remember OIL RIG: Oxidation Is Loss, Reduction Is Gain."),
        q("redox_p1",.redox,.planning,3,"Plan an experiment to compare the reducing ability of two metals using displacement reactions.","Place equal amounts/concentrations of suitable metal-ion solutions in labelled tubes; add equal-sized cleaned metal samples; observe displacement and compare which metal is oxidised.","Changing several variables between the tests.","Control concentration, volume, temperature and sample size where relevant."),
        q("redox_ace2",.redox,.ace,3,"In electrolysis of aqueous copper(II) sulfate using inert electrodes, what happens at the cathode and why?","Cu²⁺ ions gain electrons at the cathode to form copper: Cu²⁺ + 2e⁻ → Cu. Reduction occurs at the cathode.","Saying oxidation occurs at the cathode.","Reduction occurs at the cathode."),

        // Periodic
        q("period_p1",.periodic,.planning,2,"How could you compare the reactivity of two Group 1 metals using their reactions with water safely?","Use small, comparable pieces under controlled conditions and observe reaction intensity, while following laboratory safety procedures.","Using large pieces of reactive metal.","Compare under controlled amounts and conditions."),
        q("period_ace1",.periodic,.ace,2,"Explain why Group 1 metals become more reactive down the group.","The outer electron is farther from the nucleus and more shielded, so it is easier to lose.","Saying there are simply more electron shells without linking to electron loss.","Relate the trend to attraction between nucleus and outer electron."),
        q("period_ace2",.periodic,.ace,2,"Why are noble gases generally unreactive?","They have a stable outer electron arrangement, so they have little tendency to gain or lose electrons.","They have no electrons.","They do have electrons; their outer shell is stable."),

        // Energetics
        q("energy_p1",.energetics,.planning,3,"Plan an experiment to compare the temperature change for two reactions using a simple calorimetry setup.","Use equal volumes and known concentrations where appropriate; measure initial temperature; mix in an insulated container; record the maximum/minimum temperature; repeat and compare ΔT.","Using different starting temperatures without control.","Use insulation, consistent volumes/concentrations and repeat measurements."),
        q("energy_pdo1",.energetics,.pdo,2,"A reaction gives a temperature rise of 8.4 °C. State whether it is exothermic or endothermic and justify.","Exothermic, because heat is released to the surroundings and the measured solution temperature increases.","Calling it endothermic because temperature changed.","Look at the direction of temperature change of the surroundings/solution."),
        q("energy_ace1",.energetics,.ace,3,"Why does a catalyst not change the overall energy change of a reaction?","A catalyst provides an alternative pathway with lower activation energy but does not change the energy difference between reactants and products.","Saying the catalyst adds energy to the reaction.","Distinguish activation energy from overall energy change."),

        // Rate
        q("rate_p1",.rate,.planning,3,"Plan an experiment to investigate the effect of concentration on the rate of a reaction that produces a gas.","Use several concentrations while keeping total volume, temperature, reactant identity and apparatus consistent; measure gas volume at regular times or measure time for a fixed volume; repeat.","Changing concentration and temperature together.","Only the independent variable should change."),
        q("rate_pdo1",.rate,.pdo,2,"A volume-of-gas vs time graph is steep at the start and becomes less steep later. What does this show?","The reaction is fastest initially and slows down as reactants are consumed.","Saying the reaction stops immediately.","Gradient represents rate for a volume-time graph."),
        q("rate_ace1",.rate,.ace,2,"Explain why increasing temperature usually increases reaction rate.","Particles have greater kinetic energy and a greater fraction of collisions have energy equal to or above the activation energy.","Saying particles collide less often.","Use successful collisions and activation energy."),

        // Organic
        q("org_p1",.organic,.planning,3,"Describe a test for an alkene using aqueous bromine.","Add aqueous bromine to the sample. An alkene decolourises the bromine from orange/brown to colourless.","Saying all hydrocarbons decolourise bromine.","The test detects unsaturation/C=C under the syllabus conditions."),
        q("org_m1",.organic,.mmo,2,"What observation would support complete combustion of a hydrocarbon?","A blue flame/clean combustion with carbon dioxide and water as products; carbon dioxide can be confirmed with limewater.","Using flame colour alone as proof of complete combustion.","Where appropriate, confirm carbon dioxide with limewater."),
        q("org_ace1",.organic,.ace,3,"Explain why cracking is used in the petrochemical industry.","Cracking converts larger hydrocarbon molecules into smaller, more useful hydrocarbons including alkenes, increasing the supply of useful products.","Saying cracking simply burns crude oil.","Mention thermal decomposition and useful smaller molecules."),

        // Air quality
        q("air_p1",.airQuality,.planning,3,"Design a fair comparison of particulate pollution produced by two fuels.","Burn equal masses under comparable conditions and collect particulates using the same collection method; compare mass or darkness of the collected deposit.","Changing fuel mass and collection conditions at the same time.","Control the amount of fuel and collection geometry."),
        q("air_ace1",.airQuality,.ace,3,"Explain how sulfur dioxide can contribute to acid rain and one environmental effect.","Sulfur dioxide can be oxidised and dissolve/react in atmospheric water to form acidic substances; acid deposition can damage vegetation, aquatic ecosystems and limestone structures.","Saying sulfur dioxide itself is an acid.","Describe atmospheric oxidation/dissolution and an effect."),
        q("air_ace2",.airQuality,.ace,2,"Give two ways to reduce carbon dioxide emissions from energy use.","Use lower-carbon/renewable energy sources and improve energy efficiency; other valid approaches include reducing fossil-fuel use.","Saying 'plant trees' as the only method without addressing emissions.","Separate reducing emissions from removing carbon dioxide."),

        // Cross-topic exam skills
        q("skill_m1",.generalMeasurement,.mmo,2,"Why should a burette be rinsed with the solution that will be placed in it before the titration?","To avoid dilution or contamination by residual water.","Because it makes the burette cleaner only.","The rinse prevents the delivered solution concentration from being unintentionally changed."),
        q("skill_pdo1",.generalGraph,.pdo,2,"State three good practices when plotting a graph from practical data.","Label axes with quantity/unit, choose a sensible scale using most of the grid, and plot points accurately with a clear best-fit line where appropriate.","Joining every point dot-to-dot.","Use the plotted data to show the trend, not to connect every point."),
        q("skill_ace1",.generalGraph,.ace,2,"A result is far from the trend of the other readings. What should you do before deciding it is an anomaly?","Check the raw observation/calculation and apparatus; if there is evidence it is anomalous, identify it clearly and consider its effect on the conclusion.","Delete any inconvenient point automatically.","An anomaly should be justified, not simply removed."),
        q("skill_plan1",.generalPlanning,.planning,3,"For an investigation, distinguish the independent, dependent and controlled variables.","Independent: deliberately changed. Dependent: measured response. Controlled: factors kept constant to make the comparison fair.","Calling every measured quantity a controlled variable.","State exactly what is changed, measured and kept constant."),
        q("skill_ace2",.generalPlanning,.ace,3,"Give two useful ways to improve the reliability of a practical result.","Repeat measurements and use concordant/consistent results; investigate anomalies rather than averaging blindly.","Saying only 'be more careful'.","Name a concrete action and its purpose."),
        q("salt_p1",.salts,.planning,3,"Plan how to prepare a pure sample of a soluble salt from an acid and a soluble alkali.","Use titration to find exact reacting volumes with indicator, repeat without indicator using those volumes, mix the measured reactants, then evaporate some water and crystallise the salt; filter and dry crystals.","Adding excess acid or alkali when a pure soluble salt is required.","Titration is used to find the stoichiometric volumes without leaving an unwanted reagent."),
        q("salt_ace1",.salts,.ace,2,"Why are crystals washed with a small amount of cold distilled water before drying?","To remove soluble impurities while minimising loss of the desired crystals by dissolution.","Washing with a large amount of hot water.","Use a small amount of cold solvent to limit product loss."),
        q("ammonia_ace1",.ammonia,.ace,2,"State the reactants and one industrial condition used in the Haber process.","Nitrogen and hydrogen react reversibly to form ammonia; industrial conditions include elevated pressure, elevated temperature and an iron catalyst.","Saying oxygen is a reactant.","The feed gases are nitrogen and hydrogen."),

        // Mixed data-based
        q("data1",.dataBased,.pdo,3,"A student obtains titres of 24.10, 24.15, 24.55 and 24.10 cm³. Which readings should be used as concordant titres?","24.10, 24.15 and 24.10 cm³ are concordant within 0.20 cm³; 24.55 cm³ is not concordant with them.","Averaging all four automatically.","Identify concordant values before calculating the mean."),
        q("data2",.dataBased,.ace,3,"A reaction's measured rate increases when temperature is raised from 25 °C to 35 °C. Can the result alone prove that temperature is the only cause?","No. The conclusion is valid only if other relevant variables were controlled. The experiment supports an effect of temperature under the stated conditions.","Yes, because the temperature changed.","A fair test requires control of other variables."),
        q("safety1",.safety,.planning,2,"State two good laboratory precautions when heating a chemical mixture.","Use appropriate eye protection and heating apparatus; keep flammable materials away and handle hot apparatus with suitable tools.","Generic 'be careful'.","A precaution should be a specific action that reduces a stated risk.")
    ]

    static func forCurriculum(_ c: Curriculum) -> [AceQuestion] { realExpanded }
    static func forTopic(_ t: AceTopic, curriculum: Curriculum) -> [AceQuestion] { realExpanded.filter{$0.topic == t} }
    static func forSkill(_ s: AceSkillArea, curriculum: Curriculum) -> [AceQuestion] { realExpanded.filter{$0.skillArea == s} }

    private static func q(_ id:String,_ topic:AceTopic,_ skill:AceSkillArea,_ marks:Int,_ text:String,_ answer:String,_ mistakes:String,_ tip:String)->AceQuestion {
        AceQuestion(id:id,topic:topic,skillArea:skill,difficulty:marks >= 3 ? .challenging : .standard,marks:marks,questionText:text,modelAnswer:answer,commonMistakes:mistakes,examinerTip:tip)
    }
}
