import Foundation

struct UpgradeResource: Identifiable, Codable, Hashable { let id: String; let title: String; let summary: String; let items: [String] }

enum CompleteUpgradeCatalog {
    static let resources: [UpgradeResource] = [
        .init(id: "qa-cations", title: "Cation analysis", summary: "Add aqueous sodium hydroxide dropwise and in excess; record precipitate colour and solubility.", items: ["NH₄⁺: warm with sodium hydroxide; ammonia turns damp red litmus blue.", "Cu²⁺: light blue precipitate, insoluble in excess.", "Fe²⁺: green precipitate, insoluble in excess.", "Fe³⁺: red-brown precipitate, insoluble in excess.", "Zn²⁺: white precipitate, soluble in excess.", "Al³⁺: white precipitate, soluble in excess.", "Ca²⁺: white precipitate or no obvious precipitate at low concentration; use flame test orange-red.", "Ba²⁺: white precipitate; flame test apple green.", "Na⁺/K⁺: no characteristic hydroxide precipitate; flame tests yellow/lilac."]),
        .init(id: "qa-anions", title: "Anion analysis", summary: "Use separate portions of the unknown and record reagent, observation and conclusion.", items: ["Carbonate: add dilute acid; carbon dioxide turns limewater milky.", "Sulfate: acidify, then add barium nitrate; white precipitate.", "Chloride: acidify with nitric acid, then add silver nitrate; white precipitate.", "Bromide: cream precipitate with silver nitrate.", "Iodide: yellow precipitate with silver nitrate.", "Nitrate: use the prescribed nitrate test and record the positive observation.", "Phosphate: use the prescribed phosphate reagent and record the positive observation."]),
        .init(id: "qa-gases", title: "Gas tests", summary: "Confirm gases using the appropriate splint, litmus or reagent.", items: ["Hydrogen: lighted splint gives a squeaky pop.", "Oxygen: glowing splint relights.", "Carbon dioxide: limewater turns milky.", "Ammonia: damp red litmus turns blue.", "Chlorine: damp litmus is bleached.", "Sulfur dioxide: acidified potassium manganate(VII) is decolourised."]),
        .init(id: "data", title: "Data presentation", summary: "Practise tables, precision, anomalies, graphs and conclusions.", items: ["Put quantities and units in headings.", "Record repeated readings at consistent precision.", "Calculate titre as final minus initial burette reading.", "Use a sensible scale and most of the graph grid.", "Plot small, accurate crosses and draw a justified best-fit line.", "Check anomalies against the raw observation before excluding them.", "Interpolate within the measured range and label extrapolation clearly."]),
        .init(id: "academy", title: "Practical Academy", summary: "Use the procedure, evidence, calculation and evaluation pattern for every practical.", items: ["Identify the independent, dependent and controlled variables.", "List apparatus and chemicals with relevant hazards.", "Write numbered steps in the order performed.", "Provide a results table before collecting data.", "Show a worked calculation with units and appropriate precision.", "State a conclusion supported by the data.", "Give a specific limitation and an improvement with justification."]),
        .init(id: "mock", title: "Structured mock exam", summary: "Use a full 40-mark, 110-minute Paper 3-style session with five compulsory practical questions.", items: ["Question 1: quantitative practical, 15 marks.", "Question 2: qualitative analysis and observations, 12 marks.", "Question 3: data presentation and evaluation, 13 marks.", "Record time spent per question.", "Self-assess against the model answer and mark allocation.", "Review weak skill areas after submission."])
    ]
}
