//
//  ExpandedAceQuestions.swift
//  ChemistryCoach
//
//  100 real exam-style ACE questions for Singapore GCE O-Level Chemistry
//  (6092) Paper 3 Practical, covering all 13 topic areas and all 4 skill
//  strands (Planning, MMO, PDO, ACE).
//
//  These questions replace the 180 generic template questions previously
//  generated programmatically in P0ContentExpansion.swift.
//

import Foundation

extension AceQuestionBank {

    private static func q(_ id: String, _ topic: AceTopic, _ skill: AceSkillArea, _ marks: Int, _ text: String, _ answer: String, _ mistakes: String, _ tip: String) -> AceQuestion {
        AceQuestion(id: id, topic: topic, skillArea: skill, difficulty: marks >= 3 ? .challenging : .standard, marks: marks, questionText: text, modelAnswer: answer, commonMistakes: mistakes, examinerTip: tip)
    }

    static let realExpandedQuestions: [AceQuestion] = [
        // ================================================================
        // EXPERIMENTAL CHEMISTRY (8 questions)
        // ================================================================
        q("exp_r1", .experimental, .planning, 2, "A student is given a mixture of sand and sodium chloride. Describe how to obtain a pure, dry sample of sodium chloride.", "Add water and stir to dissolve the sodium chloride; filter through filter paper to remove sand (residue); collect the filtrate; heat the filtrate to evaporate some water, then allow to cool and crystallise; filter the crystals; dry between sheets of filter paper.", "Saying 'filter the mixture' without first dissolving the salt, or evaporating to dryness instead of crystallising.", "Crystallisation gives purer crystals than evaporation to dryness; evaporation to dryness can trap impurities."),
        q("exp_r2", .experimental, .mmo, 2, "A student reads a burette and records the volume as 24.5 cm³. State the correct precision for a burette reading.", "Burette readings should be recorded to the nearest 0.05 cm³ (two decimal places), e.g. 24.50 cm³. The student recorded only one decimal place, losing precision.", "Recording only one decimal place or rounding to the nearest 0.1 cm³.", "Always read the burette to two decimal places; read the bottom of the meniscus at eye level."),
        q("exp_r3", .experimental, .ace, 2, "A student has two white solids, one pure and one impure. Explain how measuring the melting point can distinguish them.", "The pure substance has a sharp melting point at a specific temperature. The impure substance melts over a range of temperatures and at a lower temperature than the pure substance.", "Saying the impure substance has a higher melting point.", "Impurities lower the melting point and broaden the melting range."),
        q("exp_r4", .experimental, .pdo, 3, "Describe the apparatus needed for simple distillation and state where the thermometer bulb should be positioned.", "Round-bottom flask (containing the mixture) on a heat source; still head connecting to a condenser; thermometer with its bulb at the still head (not in the liquid); condenser with water entering at the bottom and exiting at the top; collection flask/beaker at the end of the condenser.", "Placing the thermometer bulb in the liquid, or showing water entering the condenser at the top.", "Thermometer bulb goes at the still head so it measures the temperature of the vapour being condensed; water enters at the bottom for counter-current cooling."),
        q("exp_r5", .experimental, .mmo, 2, "Describe how to use a pipette to measure 25.0 cm³ of a solution accurately.", "Use a pipette filler to draw the solution up to the 25.0 cm³ calibration mark; read the bottom of the meniscus at eye level; release the solution into the conical flask; allow the last drop to drain naturally — do not blow it out.", "Blowing out the residual drop from a standard pipette, or using a measuring cylinder instead.", "Use a pipette filler for safety; the calibration mark accounts for the residual drop in a standard pipette."),
        q("exp_r6", .experimental, .ace, 3, "Explain why crystallisation is preferred over evaporation to dryness for obtaining pure sodium chloride crystals from aqueous solution.", "Evaporation to dryness would give a powder that may retain soluble impurities and may lose water of crystallisation. Crystallisation produces larger, purer crystals: the solution is heated to evaporate some water, then allowed to cool so crystals form slowly, leaving impurities dissolved in the remaining solution.", "Saying evaporation to dryness gives the same result as crystallisation.", "Slow crystallisation rejects impurities from the crystal lattice, giving a purer product than evaporation to dryness."),
        q("exp_r7", .experimental, .pdo, 2, "In paper chromatography, a spot travels 3.6 cm while the solvent front travels 9.0 cm. Calculate the Rf value.", "Rf = distance travelled by spot / distance travelled by solvent front = 3.6 / 9.0 = 0.40.", "Multiplying instead of dividing, or giving Rf a unit.", "Rf is always between 0 and 1 and has no units."),
        q("exp_r8", .experimental, .planning, 3, "Plan an experiment to obtain pure water from seawater using simple distillation.", "Pour seawater into a round-bottom flask (about half full); set up the distillation apparatus with a thermometer at the still head, condenser, and collection beaker; heat the seawater gently using a Bunsen burner; water vapour rises, enters the condenser where it condenses; collect the distilled water in a clean beaker. The salt remains in the flask.", "Heating too strongly (may cause bumping) or not connecting the condenser water correctly.", "Water enters the condenser at the bottom and exits at the top for efficient cooling; heat gently to avoid splashing."),

        // ================================================================
        // PARTICULATE NATURE OF MATTER (8 questions)
        // ================================================================
        q("part_r1", .particulate, .planning, 2, "Describe an experiment to show that particles in a gas are in constant random motion.", "Place cotton wool soaked in concentrated ammonia solution at one end of a glass tube and cotton wool soaked in concentrated hydrochloric acid at the other end. A white ring of ammonium chloride forms inside the tube, showing that both gases diffuse through the air and meet.", "Not explaining that the white ring shows where the diffusing particles met.", "The white ring of NH₄Cl forms closer to the HCl end because NH₃ (Mr = 17) diffuses faster than HCl (Mr = 36.5)."),
        q("part_r2", .particulate, .mmo, 2, "In the diffusion experiment with NH₃ and HCl, state the observation and what it demonstrates.", "A white ring of ammonium chloride (NH₄Cl) appears inside the tube, closer to the HCl end. This shows that both gases diffuse through the air and react where their particles meet.", "Saying the white ring appears exactly in the middle of the tube.", "NH₃ (Mr = 17) diffuses faster than HCl (Mr = 36.5), so the ring forms closer to the HCl end."),
        q("part_r3", .particulate, .ace, 3, "Explain why ammonia gas diffuses faster than hydrogen chloride gas, using the kinetic particle model.", "Ammonia (NH₃, Mr = 17) has a lower relative molecular mass than hydrogen chloride (HCl, Mr = 36.5). At the same temperature, all gas particles have the same average kinetic energy, so lighter particles move faster on average and diffuse more quickly.", "Saying ammonia has more energy or that the temperature is different for each gas.", "At the same temperature, lighter gas particles travel faster on average (same average KE, lower mass → higher average speed)."),
        q("part_r4", .particulate, .pdo, 2, "Describe the arrangement and movement of particles in a solid, a liquid, and a gas.", "Solid: particles closely packed in a regular lattice, vibrating about fixed positions. Liquid: particles close together but disordered, able to slide past one another. Gas: particles far apart, randomly arranged, moving quickly in all directions.", "Saying gas particles are stationary or that solid particles do not move at all.", "All particles move; the type of motion differs (vibration in solids, translational motion in liquids and gases)."),
        q("part_r5", .particulate, .mmo, 2, "A student compresses a gas in a syringe. Explain the observation at the particle level.", "The gas is compressible because there are large spaces between gas particles. When pressure is applied, particles are forced closer together, reducing the volume. The particles themselves are not compressed.", "Saying the particles themselves are squashed or compressed.", "It is the spaces between particles that are reduced, not the particles themselves."),
        q("part_r6", .particulate, .ace, 2, "Explain why evaporation causes cooling, using the kinetic particle theory.", "The fastest-moving particles (with the highest kinetic energy) escape from the liquid surface first. The remaining particles have a lower average kinetic energy, so the temperature of the liquid decreases.", "Saying particles leave randomly without linking to the energy distribution.", "Only the most energetic particles escape, lowering the average energy (and thus temperature) of those remaining."),
        q("part_r7", .particulate, .ace, 3, "A sealed balloon contains a fixed amount of gas at constant temperature. Explain what happens to the pressure when the balloon is squeezed and the volume decreases.", "Pressure increases. At constant temperature, reducing the volume means the same number of particles are in a smaller space, so they collide with the walls more frequently, increasing the pressure.", "Saying the temperature increases when the volume decreases (temperature is constant here).", "At constant temperature, pressure and volume are inversely related (Boyle's Law)."),
        q("part_r8", .particulate, .pdo, 2, "A student records: at 20 °C, a gas diffuses 10 cm in 60 s; at 40 °C, the same gas diffuses 10 cm in 40 s. What conclusion can be drawn?", "At the higher temperature, the gas diffuses faster (10 cm in 40 s vs 60 s). The rate of diffusion increases with temperature.", "Saying the distance is different (it is the same 10 cm; the time differs).", "Higher temperature → greater kinetic energy → faster particle movement → faster diffusion."),

        // ================================================================
        // CHEMICAL BONDING & STRUCTURE (7 questions)
        // ================================================================
        q("bond_r1", .bonding, .ace, 3, "Explain why molten sodium chloride conducts electricity but solid sodium chloride does not.", "In solid NaCl, the ions (Na⁺ and Cl⁻) are held in fixed positions in the ionic lattice and cannot move. In the molten state, the ions are free to move and can carry charge, so the compound conducts electricity.", "Saying electrons move through the solid, or that the solid has no ions.", "It is the ions (not electrons) that carry charge in ionic compounds; they must be mobile (molten or in solution)."),
        q("bond_r2", .bonding, .pdo, 2, "Substance A has a melting point of 801 °C. Substance B has a melting point of −78 °C. Suggest the type of structure for each.", "Substance A (801 °C, high melting point) is likely an ionic compound with a giant ionic lattice. Substance B (−78 °C, low melting point) is likely a simple molecular substance with weak intermolecular forces.", "Saying a high melting point means metallic without considering ionic.", "High melting points suggest giant structures (ionic or giant covalent); low melting points suggest simple molecular."),
        q("bond_r3", .bonding, .ace, 2, "Explain why metals are good conductors of electricity.", "Metals have delocalised (free) electrons that are able to move through the structure and carry charge when a voltage is applied.", "Saying metal ions carry the charge.", "Delocalised electrons are the charge carriers in metallic bonding."),
        q("bond_r4", .bonding, .pdo, 3, "Describe the bonding in sodium chloride (NaCl) and state how the dot-and-cross diagram should be drawn.", "Sodium (2.8.1) transfers its outer electron to chlorine (2.8.7). Na becomes Na⁺ (2.8) and Cl becomes Cl⁻ (2.8.8). The diagram shows Na⁺ with no outer electrons in brackets with a + charge, and Cl⁻ with 8 outer electrons (including the transferred electron shown as a cross) in brackets with a − charge. Electrostatic attraction between oppositely charged ions holds the lattice together.", "Drawing covalent bonds (shared electrons) instead of electron transfer, or omitting the charges.", "Ionic bonding involves electron transfer, not sharing. Show charges on the ions and brackets around each ion."),
        q("bond_r5", .bonding, .mmo, 2, "A student connects a circuit with a lamp to solid sodium chloride, then dissolves it in water. State what happens to the lamp in each case.", "Solid NaCl: the lamp does not light (ions are fixed, cannot move). Dissolved in water: the lamp lights up (ions are free to move and carry charge).", "Saying the solid NaCl conducts before water is added.", "Dissolving frees the ions; solid ionic compounds do not conduct because ions are fixed in the lattice."),
        q("bond_r6", .bonding, .ace, 3, "Both diamond and graphite are forms of carbon. Explain why diamond is hard but graphite is soft and slippery.", "In diamond, each carbon atom is bonded to four others in a rigid 3D tetrahedral lattice — all outer electrons are used in strong covalent bonds, making it very hard. In graphite, each carbon is bonded to three others in layers; the fourth electron is delocalised between layers, which are held by weak intermolecular forces, so layers can slide over each other, making graphite soft and slippery.", "Saying graphite has no covalent bonds, or that diamond has delocalised electrons.", "Diamond: 4 bonds per C (tetrahedral). Graphite: 3 bonds per C (layers) + one delocalised electron per C."),
        q("bond_r7", .bonding, .planning, 2, "Plan a simple test to determine whether an unknown solid is an ionic or simple molecular compound.", "Dissolve the solid in water and test whether the solution conducts electricity using a circuit with a lamp. If it conducts, the compound is likely ionic (ions are freed in solution). If it does not conduct, it may be simple molecular. Also check the melting point: ionic compounds have high melting points, simple molecular have low.", "Saying 'look at it' or using flammability to distinguish.", "Conductivity in solution combined with melting point data distinguishes ionic from simple molecular compounds."),

        // ================================================================
        // CHEMICAL CALCULATIONS (8 questions)
        // ================================================================
        q("calc_r1", .calculations, .ace, 3, "25.0 cm³ of 0.100 mol/dm³ NaOH is neutralised by 22.40 cm³ of HCl. Calculate the concentration of HCl.", "Equation: HCl + NaOH → NaCl + H₂O (1:1 ratio). Moles NaOH = 0.100 × 0.0250 = 0.00250 mol. Moles HCl = 0.00250 mol (1:1). Volume HCl = 22.40 cm³ = 0.02240 dm³. Concentration = 0.00250 / 0.02240 = 0.112 mol/dm³.", "Forgetting to convert cm³ to dm³, or using the wrong mole ratio.", "Always write the balanced equation first to get the mole ratio; convert cm³ to dm³ by dividing by 1000."),
        q("calc_r2", .calculations, .pdo, 3, "A student titrates H₂SO₄ against 25.0 cm³ of 0.200 mol/dm³ NaOH. The titres are: 18.60, 18.55, 18.90, 18.50 cm³. Identify the concordant titres, calculate the mean, and find the concentration of H₂SO₄.", "Concordant titres: 18.60, 18.55, and 18.50 cm³ (within 0.20 cm³ of each other); 18.90 is anomalous. Mean = (18.60 + 18.55 + 18.50)/3 = 18.55 cm³. Equation: H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O. Moles NaOH = 0.200 × 0.0250 = 0.00500 mol. Ratio 1:2, so moles H₂SO₄ = 0.00500/2 = 0.00250 mol. Concentration = 0.00250/0.01855 = 0.135 mol/dm³.", "Averaging all four titres including the anomalous one, or using a 1:1 ratio instead of 1:2.", "Identify concordant titres (within 0.20 cm³) before calculating the mean; check the mole ratio from the balanced equation."),
        q("calc_r3", .calculations, .ace, 3, "Calculate the volume of 0.250 mol/dm³ HNO₃ required to react completely with 40.0 cm³ of 0.150 mol/dm³ Ca(OH)₂.", "Equation: 2HNO₃ + Ca(OH)₂ → Ca(NO₃)₂ + 2H₂O. Moles Ca(OH)₂ = 0.150 × 0.0400 = 0.00600 mol. Ratio HNO₃:Ca(OH)₂ = 2:1, so moles HNO₃ = 2 × 0.00600 = 0.0120 mol. Volume = 0.0120/0.250 = 0.0480 dm³ = 48.0 cm³.", "Using a 1:1 ratio instead of 2:1 from the balanced equation.", "Write the balanced equation first; the ratio 2:1 means you need twice the moles of HNO₃."),
        q("calc_r4", .calculations, .ace, 3, "25.0 cm³ of 0.500 mol/dm³ NaOH reacts with excess HCl. Calculate the mass of NaCl formed. (Mr: Na = 23, Cl = 35.5)", "Equation: HCl + NaOH → NaCl + H₂O. Moles NaOH = 0.500 × 0.0250 = 0.0125 mol. Ratio 1:1, so moles NaCl = 0.0125 mol. Mr(NaCl) = 23 + 35.5 = 58.5. Mass = 0.0125 × 58.5 = 0.731 g.", "Not writing the balanced equation, or using the wrong mole ratio.", "Show the balanced equation; calculate Mr correctly (Na = 23, Cl = 35.5)."),
        q("calc_r5", .calculations, .pdo, 2, "In a reaction, the theoretical yield of product is 16.7 g but the actual yield is 12.5 g. Calculate the percentage yield.", "Percentage yield = (actual yield / theoretical yield) × 100 = (12.5 / 16.7) × 100 = 74.9% (≈ 75%).", "Swapping actual and theoretical yield, or forgetting to multiply by 100.", "Actual yield is always ≤ theoretical yield; the formula is actual/theoretical × 100."),
        q("calc_r6", .calculations, .ace, 2, "An impure 10.0 g sample of CaCO₃ reacts with excess acid to produce 2.20 g of CO₂. Calculate the percentage purity. (Mr: Ca = 40, C = 12, O = 16)", "Equation: CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂. Mr(CO₂) = 44; Mr(CaCO₃) = 100. Moles CO₂ = 2.20/44 = 0.0500 mol. Ratio 1:1, so moles CaCO₃ = 0.0500 mol. Mass of pure CaCO₃ = 0.0500 × 100 = 5.00 g. Percentage purity = (5.00/10.0) × 100 = 50.0%.", "Confusing percentage purity with percentage yield.", "Purity compares pure mass to total sample mass; only the pure CaCO₃ produces CO₂."),
        q("calc_r7", .calculations, .ace, 3, "11.1 g of hydrated copper(II) sulfate, CuSO₄·xH₂O, is heated to constant mass. The anhydrous salt weighs 7.09 g. Find x. (Mr: Cu = 63.5, S = 32.1, O = 16, H = 1)", "Mass of water = 11.1 − 7.09 = 4.01 g. Mr(CuSO₄) = 63.5 + 32.1 + 64 = 159.6. Moles CuSO₄ = 7.09/159.6 = 0.0444 mol. Mr(H₂O) = 18. Moles H₂O = 4.01/18 = 0.2228 mol. x = 0.2228/0.0444 = 5.02 ≈ 5. Formula: CuSO₄·5H₂O.", "Not heating to constant mass, or rounding too early in the calculation.", "Heat to constant mass to ensure all water is driven off; round to the nearest whole number only at the final step."),
        q("calc_r8", .calculations, .planning, 3, "Describe how you would determine the value of x in a hydrated salt of formula CuSO₄·xH₂O by experiment.", "Weigh an empty boiling tube (m₁). Add hydrated salt and weigh (m₂). Heat gently, cool, weigh, then reheat to constant mass (m₃). Mass of anhydrous salt = m₃ − m₁. Mass of water = m₂ − m₃. Calculate moles of anhydrous salt (mass/Mr) and moles of water (mass/18). x = moles of water / moles of anhydrous salt. Heat gently to avoid decomposing the salt.", "Not heating to constant mass, or heating too strongly (which may decompose the anhydrous salt).", "Heat gently and to constant mass; use a Bunsen burner on a low flame and hold the tube at an angle."),

        // ================================================================
        // ACID–BASE CHEMISTRY (8 questions)
        // ================================================================
        q("acid_r1", .acidBase, .mmo, 2, "State the indicator and colour change observed when titrating ethanoic acid (weak acid) against sodium hydroxide (strong alkali).", "Use phenolphthalein. The solution starts pink (alkaline) and changes to colourless at the endpoint (when the acid is in excess).", "Using methyl orange or Universal Indicator for a weak acid/strong alkali titration.", "Phenolphthalein is suitable because the endpoint is in the basic pH range (8.2–10.0)."),
        q("acid_r2", .acidBase, .ace, 2, "Explain why 0.1 mol/dm³ hydrochloric acid has a lower pH than 0.1 mol/dm³ ethanoic acid.", "HCl is a strong acid and ionises completely in water, producing a higher concentration of H⁺ ions. Ethanoic acid is a weak acid and only partially ionises, giving a lower [H⁺] at the same concentration.", "Saying strong acids have 'more acid' without referring to ionisation.", "Compare the extent of ionisation and [H⁺]; same concentration but different degree of ionisation."),
        q("acid_r3", .acidBase, .pdo, 2, "Three solutions have pH values of 1, 7, and 13. Identify each as strongly acidic, neutral, or strongly alkaline.", "pH 1 = strongly acidic; pH 7 = neutral; pH 13 = strongly alkaline.", "Confusing high pH with high acidity.", "pH < 7 = acidic; pH 7 = neutral; pH > 7 = alkaline. Lower pH = more acidic."),
        q("acid_r4", .acidBase, .mmo, 2, "Explain why a burette should be rinsed with the solution it will contain before a titration.", "If the burette still contains water from washing, it will dilute the titrant, giving a larger titre and a lower calculated concentration. Rinsing with the titrant ensures the concentration is not altered.", "Saying it makes the burette 'cleaner' without explaining the dilution effect.", "Residual water dilutes the titrant; rinse with the same solution to maintain the correct concentration."),
        q("acid_r5", .acidBase, .pdo, 2, "A student obtains titres of 24.10, 24.15, 24.55, and 24.10 cm³. Identify the concordant titres and calculate the mean.", "24.10, 24.15, and 24.10 are concordant (within 0.20 cm³ of each other). 24.55 is not concordant (0.45 cm³ from 24.10). Mean = (24.10 + 24.15 + 24.10)/3 = 24.12 cm³.", "Averaging all four titres including the anomalous 24.55.", "Concordant titres are within 0.20 cm³; discard anomalous values before averaging."),
        q("acid_r6", .acidBase, .ace, 3, "In a titration, a student reads the burette from above (looking down) instead of at eye level. Explain the effect on the recorded titre and the calculated concentration.", "Reading from above gives a falsely low burette reading (the meniscus appears higher than it is), so the recorded titre is smaller than the true value. A smaller titre leads to a higher calculated concentration of the titrant.", "Saying the error makes the result 'wrong' without explaining the direction of the effect.", "Parallax error: reading from above → lower reading → smaller titre → higher calculated concentration."),
        q("acid_r7", .acidBase, .planning, 3, "Describe how to prepare 250 cm³ of 0.100 mol/dm³ sodium hydroxide solution from solid NaOH. (Mr: Na = 23, O = 16, H = 1)", "Mass needed: 0.100 × 0.250 × 40 = 1.00 g. Weigh 1.00 g of solid NaOH using a balance. Dissolve in distilled water in a beaker. Transfer to a 250 cm³ volumetric flask, washing the beaker with distilled water into the flask. Add distilled water to the mark (bottom of meniscus on the line at eye level). Stopper and invert to mix.", "Not using a volumetric flask, or not washing the beaker into the flask.", "Use a volumetric flask for accuracy; wash all transfers into the flask; read the meniscus at eye level."),
        q("acid_r8", .acidBase, .mmo, 2, "State the colour change observed when titrating HCl (in the burette) into NaOH using methyl orange indicator.", "The solution starts yellow (alkaline) and changes to orange/red at the endpoint (acidic), indicating neutralisation.", "Using phenolphthalein and describing the wrong colour change, or not knowing the endpoint colour.", "Methyl orange: yellow in alkali, red in acid; the endpoint is orange."),

        // ================================================================
        // QUALITATIVE ANALYSIS (8 questions)
        // ================================================================
        q("qual_r1", .qualitative, .ace, 2, "Describe the test for chloride ions in a solution and state the observation.", "Acidify the solution with dilute nitric acid, then add aqueous silver nitrate (AgNO₃). A white precipitate insoluble in dilute nitric acid indicates chloride ions (AgCl).", "Using hydrochloric acid to acidify (it introduces Cl⁻ and gives a false positive).", "Always acidify with dilute HNO₃ before adding AgNO₃ — all nitrates are soluble, so no false precipitate."),
        q("qual_r2", .qualitative, .mmo, 2, "A student adds dilute acid to a white solid. Effervescence occurs and the gas turns limewater milky. State the observation and inference.", "Observation: effervescence (bubbles of gas); the gas turns limewater from colourless to milky. Inference: carbonate ion (CO₃²⁻) is present; the gas is carbon dioxide.", "Saying 'bubbles form' without testing or identifying the gas.", "Always test the gas — for carbonate, the gas is CO₂ confirmed by limewater turning milky."),
        q("qual_r3", .qualitative, .ace, 3, "A solution gives a white precipitate with aqueous NaOH that dissolves in excess NaOH. Describe how to determine whether the cation is Al³⁺ or Zn²⁺.", "Add aqueous ammonia (NH₃) to a fresh portion of the solution. If Al³⁺: a white precipitate forms that is insoluble in excess NH₃. If Zn²⁺: a white precipitate forms that dissolves in excess NH₃ to give a colourless solution.", "Concluding Al³⁺ or Zn²⁺ from the NaOH test alone without using NH₃.", "Both Al³⁺ and Zn²⁺ give a white ppt soluble in excess NaOH; only NH₃ distinguishes them."),
        q("qual_r4", .qualitative, .mmo, 2, "A solution of an unknown salt gives a light blue precipitate with aqueous NaOH, insoluble in excess. State the observation and inference.", "Observation: light blue precipitate forms, insoluble in excess NaOH. Inference: copper(II) ion (Cu²⁺) is present.", "Saying the precipitate is green or soluble in excess.", "Cu²⁺ gives a light blue precipitate with NaOH that does not dissolve in excess."),
        q("qual_r5", .qualitative, .pdo, 2, "A student carries out flame tests on four compounds and records: A = crimson red, B = bright yellow, C = lilac, D = orange-red. Identify the cation in each.", "A = lithium (Li⁺); B = sodium (Na⁺); C = potassium (K⁺); D = calcium (Ca²⁺).", "Confusing lithium (crimson) with calcium (orange-red), or sodium (yellow) with calcium.", "Use the mnemonic: Li = crimson, Na = yellow, K = lilac, Ca = orange-red, Ba = green, Cu = blue-green."),
        q("qual_r6", .qualitative, .ace, 2, "Describe the test for sulfate ions (SO₄²⁻) and state the expected observation.", "Acidify the solution with dilute nitric acid, then add barium nitrate solution. A white precipitate insoluble in dilute nitric acid indicates sulfate ions (BaSO₄).", "Using sulfuric acid to acidify (it introduces sulfate ions and gives a false positive).", "Acidify with HNO₃ first; BaSO₄ is insoluble and appears as a white precipitate."),
        q("qual_r7", .qualitative, .mmo, 3, "Describe the test for nitrate ions (NO₃⁻) in a solution, including reagents and the expected observation.", "Add sodium hydroxide (NaOH) and a small piece of aluminium foil to the solution. Warm gently. A pungent gas is produced that turns damp red litmus paper blue. This confirms nitrate ions (the gas is ammonia).", "Forgetting to add aluminium foil, or not warming the mixture.", "Both NaOH and aluminium foil are needed; warming releases the NH₃ gas which turns damp red litmus blue."),
        q("qual_r8", .qualitative, .ace, 3, "A student writes: 'Chloride ion is present.' State whether this is an observation or an inference, and explain the difference.", "This is an inference — it is a conclusion drawn from the observation. An observation is what you see (e.g. 'a white precipitate formed'). The inference is the conclusion drawn from it (e.g. 'chloride ions are present'). Always record the observation first, then state the inference.", "Writing inferences as if they are observations.", "Observations = what you see/hear/smell. Inferences = conclusions drawn from the observations."),

        // ================================================================
        // REDOX CHEMISTRY (8 questions)
        // ================================================================
        q("redox_r1", .redox, .ace, 3, "Predict the products at each electrode during the electrolysis of molten lead(II) bromide (PbBr₂). Include half-equations.", "Cathode (−): Pb²⁺ ions gain electrons (reduction): Pb²⁺ + 2e⁻ → Pb. Grey lead metal forms. Anode (+): Br⁻ ions lose electrons (oxidation): 2Br⁻ → Br₂ + 2e⁻. Brown bromine vapour is produced.", "Reversing anode and cathode, or saying electrons flow through the electrolyte.", "Anode = oxidation; cathode = reduction. In molten electrolytes, only the compound's own ions are present."),
        q("redox_r2", .redox, .mmo, 3, "Describe the observations at each electrode during the electrolysis of aqueous copper(II) sulfate with inert (carbon) electrodes.", "Cathode: reddish-brown deposit of copper metal forms on the electrode. Anode: bubbles of colourless gas (oxygen) are produced; the gas relights a glowing splint. The blue colour of the solution fades as Cu²⁺ ions are removed.", "Not stating observations (e.g. just saying 'copper is formed' without describing the reddish-brown deposit).", "Cu²⁺ is below H in the reactivity series, so Cu is discharged at the cathode. At the anode, OH⁻ is discharged (no halide present) to give O₂."),
        q("redox_r3", .redox, .ace, 3, "Explain the difference in products at the anode when electrolysis is carried out on (a) concentrated NaCl solution and (b) dilute NaCl solution.", "(a) Concentrated NaCl: Cl⁻ is in high concentration, so chlorine gas is discharged at the anode (2Cl⁻ → Cl₂ + 2e⁻). (b) Dilute NaCl: Cl⁻ concentration is too low, so OH⁻ is discharged instead, producing oxygen (4OH⁻ → O₂ + 2H₂O + 4e⁻).", "Saying the same product forms in both cases, or not linking concentration to the product.", "Concentration matters for halides: high concentration → halide discharged; dilute → oxygen from OH⁻."),
        q("redox_r4", .redox, .pdo, 2, "Write the half-equation for the reaction at the cathode during the electrolysis of aqueous silver nitrate using inert electrodes.", "Ag⁺(aq) + e⁻ → Ag(s). Silver ions gain one electron each (reduction) to form silver metal.", "Forgetting the electrons, or not balancing the charge.", "Ag⁺ has a +1 charge, so it gains 1 electron. Reduction = gain of electrons (electrons on the left)."),
        q("redox_r5", .redox, .mmo, 2, "A student places a strip of zinc into a copper(II) sulfate solution. State the observation and explain.", "A reddish-brown deposit of copper forms on the zinc strip. The blue colour of the solution fades. Zinc is more reactive than copper, so zinc displaces copper: Zn + CuSO₄ → ZnSO₄ + Cu.", "Saying copper displaces zinc (wrong direction — Zn is more reactive).", "More reactive metals displace less reactive metals from their salt solutions."),
        q("redox_r6", .redox, .ace, 2, "Predict the product at the cathode when aqueous sodium sulfate (Na₂SO₄) is electrolysed with inert electrodes.", "Hydrogen gas is produced at the cathode. Na⁺ is above hydrogen in the reactivity series, so H⁺ (from water) is discharged instead: 2H⁺ + 2e⁻ → H₂.", "Saying sodium metal is produced at the cathode.", "Metals above H in the reactivity series → H₂ is discharged at the cathode in aqueous solution."),
        q("redox_r7", .redox, .mmo, 2, "During the electrolysis of dilute sulfuric acid, state the observation at the anode and identify the gas.", "Bubbles of colourless gas are produced at the anode. The gas relights a glowing splint, confirming it is oxygen (from the discharge of OH⁻ ions).", "Saying chlorine is produced (there is no chloride in sulfuric acid).", "No halide present → OH⁻ is discharged → O₂. Test with a glowing splint (relights)."),
        q("redox_r8", .redox, .ace, 3, "During the electrolysis of aqueous copper(II) sulfate with inert electrodes, the blue solution gradually becomes colourless. Explain this observation.", "Copper(II) ions (Cu²⁺) are responsible for the blue colour. At the cathode, Cu²⁺ ions gain electrons and are deposited as copper metal, so they are removed from the solution. As the concentration of Cu²⁺ decreases, the blue colour fades. The solution becomes acidic as H⁺ and SO₄²⁻ remain.", "Saying the solution becomes alkaline.", "The solution becomes more acidic: Cu²⁺ is removed (colour fades) but H⁺ and SO₄²⁻ remain, and water is consumed at the anode."),

        // ================================================================
        // PERIODIC TABLE (7 questions)
        // ================================================================
        q("period_r1", .periodic, .ace, 2, "Explain why Group 1 metals become more reactive going down the group.", "As you go down Group 1, the outer electron is in a higher energy level, farther from the nucleus and more shielded by inner electrons. The attraction between the nucleus and the outer electron decreases, so the electron is lost more easily and reactivity increases.", "Saying there are 'more electrons' without linking to the ease of electron loss.", "Reactivity increases down Group 1 because the outer electron is easier to lose (farther from nucleus, more shielding)."),
        q("period_r2", .periodic, .mmo, 2, "Describe what you would observe when a small piece of potassium is added to water.", "Potassium floats on the water, moves rapidly, and reacts vigorously with a lilac flame. Hydrogen gas is produced (pop with a lighted splint) and potassium hydroxide is formed, making the solution alkaline.", "Saying the flame is yellow (that is sodium, not potassium).", "Potassium gives a lilac flame; the reaction is more vigorous than with sodium."),
        q("period_r3", .periodic, .ace, 3, "Chlorine water is added to potassium bromide solution and to potassium iodide solution. Describe the observations and explain using the reactivity series.", "Chlorine is more reactive than bromine and iodine. With KBr: chlorine displaces bromine — the solution turns orange/brown. With KI: chlorine displaces iodine — the solution turns dark brown/black. Equations: Cl₂ + 2KBr → 2KCl + Br₂; Cl₂ + 2KI → 2KCl + I₂.", "Saying bromine displaces chlorine (wrong direction — Cl is more reactive).", "A more reactive halogen displaces a less reactive one from its salt solution."),
        q("period_r4", .periodic, .ace, 2, "Explain why noble gases such as argon are unreactive.", "Noble gases have a complete (stable) outer electron shell. They have no tendency to gain, lose, or share electrons, so they are chemically unreactive.", "Saying noble gases have no electrons.", "Noble gases do have electrons — their outer shell is full and stable, giving no tendency to react."),
        q("period_r5", .periodic, .pdo, 2, "The table shows properties of two elements: Element X — high melting point, good electrical conductor, forms coloured compounds. Element Y — low melting point, non-conductor. Classify each.", "Element X is a transition metal (high melting point, conducts electricity, forms coloured compounds — characteristic properties of transition metals). Element Y is a non-metal (low melting point, non-conductor).", "Saying all metals form coloured compounds (only transition metals typically do).", "Transition metals: high melting point, good conductors, form coloured compounds, can act as catalysts."),
        q("period_r6", .periodic, .ace, 3, "Explain why the reactivity of Group 7 elements (halogens) decreases going down the group.", "Going down Group 7, the outer shell is farther from the nucleus and more shielded by inner electrons. Gaining an electron becomes harder because the nuclear attraction on the incoming electron decreases. Therefore, reactivity decreases down the group.", "Saying reactivity increases down Group 7 (confusing with Group 1).", "Group 1: reactivity increases downward (losing electron easier). Group 7: reactivity decreases downward (gaining electron harder)."),
        q("period_r7", .periodic, .planning, 2, "Plan a safe experiment to compare the reactivity of lithium and sodium with water.", "Use small, equal-sized pieces (pea-sized) of each metal. Add each separately to a trough of water with universal indicator. Observe the reaction rate and intensity. Lithium fizzes gently; sodium reacts more vigorously, melting into a ball. Both produce hydrogen (test with a lighted splint). Wear goggles and use tongs; keep away from flammable materials.", "Using large pieces of reactive metal, or not controlling the size of each piece.", "Control: same size of metal, same volume and temperature of water. Safety: small pieces, goggles, tongs."),

        // ================================================================
        // CHEMICAL ENERGETICS (8 questions)
        // ================================================================
        q("energy_r1", .energetics, .ace, 2, "A student mixes two solutions and the temperature increases from 22.0 °C to 28.5 °C. Classify the reaction as exothermic or endothermic and justify.", "Exothermic. Heat is released to the surroundings, causing the temperature of the solution to rise. The energy of the products is lower than that of the reactants (ΔH is negative).", "Saying endothermic because the temperature 'changed'.", "Temperature increase of the surroundings/solution = exothermic; ΔH is negative."),
        q("energy_r2", .energetics, .pdo, 3, "50 cm³ of 1.00 mol/dm³ HCl is mixed with 50 cm³ of 1.00 mol/dm³ NaOH in a polystyrene cup. The temperature rises from 22.0 °C to 28.5 °C. Calculate the energy released. (c = 4.2 J/g/°C; assume 1 cm³ = 1 g)", "Total mass = 50 + 50 = 100 g. ΔT = 28.5 − 22.0 = 6.5 °C. q = m × c × ΔT = 100 × 4.2 × 6.5 = 2730 J = 2.73 kJ.", "Using only the mass of one solution (50 g instead of 100 g), or not converting J to kJ.", "Use the TOTAL mass of the solution (acid + alkali); 1 cm³ ≈ 1 g for dilute aqueous solutions."),
        q("energy_r3", .energetics, .ace, 3, "Using the data from the previous question (q = 2.73 kJ), calculate the enthalpy change of neutralisation per mole of water formed.", "Equation: HCl + NaOH → NaCl + H₂O. Moles HCl = 1.00 × 0.050 = 0.0500 mol. Moles NaOH = 1.00 × 0.050 = 0.0500 mol. Ratio 1:1, so moles H₂O = 0.0500 mol. ΔH = −q / moles = −2.73 / 0.0500 = −54.6 kJ/mol. (Negative because the reaction is exothermic; this is close to the accepted literature value of about −57 kJ/mol for strong acid-strong alkali neutralisation.)", "Forgetting the negative sign, or using the wrong number of moles.", "ΔH = −q/n; exothermic = negative sign; use the limiting reactant moles (here both are 0.0500 mol)."),
        q("energy_r4", .energetics, .ace, 3, "In the reaction H₂ + Cl₂ → 2HCl, the bond energies are: H−H = 436 kJ/mol, Cl−Cl = 242 kJ/mol, H−Cl = 431 kJ/mol. Calculate the enthalpy change.", "Energy absorbed (breaking bonds) = 436 + 242 = 678 kJ/mol. Energy released (making bonds) = 2 × 431 = 862 kJ/mol. ΔH = 678 − 862 = −184 kJ/mol. The reaction is exothermic.", "Adding instead of subtracting, or not multiplying H−Cl by 2 (two H−Cl bonds are formed).", "Bond breaking = endothermic (+); bond making = exothermic (−). ΔH = bonds broken − bonds formed."),
        q("energy_r5", .energetics, .planning, 3, "Plan an experiment to compare the temperature change when magnesium and zinc are each reacted with dilute hydrochloric acid.", "Measure equal volumes (e.g. 25 cm³) of the same concentration HCl into two polystyrene cups. Record initial temperatures. Add equal masses (e.g. 0.50 g) of magnesium and zinc separately. Stir and record the maximum temperature reached. Calculate ΔT for each. Repeat and compare. Controlled variables: volume and concentration of acid, mass of metal, same cup type, same starting temperature.", "Changing concentration and temperature at the same time, or using different masses of metal.", "Control all variables except the metal identity; use insulation (polystyrene cup with lid) and record the maximum temperature quickly."),
        q("energy_r6", .energetics, .pdo, 2, "On an energy level diagram, the reactants are at a higher energy level than the products. State whether the reaction is exothermic or endothermic and describe the direction of the ΔH arrow.", "Exothermic. The reactants are higher than the products, so energy is released. The ΔH arrow points downward from reactants to products.", "Saying the arrow points upward for exothermic.", "Reactants higher → exothermic → ΔH arrow downward. Reactants lower → endothermic → ΔH arrow upward."),
        q("energy_r7", .energetics, .ace, 2, "Explain why a catalyst increases the rate of a reaction but does not change the overall energy change (ΔH).", "A catalyst provides an alternative reaction pathway with a lower activation energy, so more collisions are successful and the rate increases. However, the energy difference between reactants and products is unchanged, so ΔH remains the same.", "Saying the catalyst adds energy to the reaction.", "Catalyst lowers activation energy (alternative pathway) but ΔH depends only on the energy of reactants and products."),
        q("energy_r8", .energetics, .mmo, 2, "When measuring the temperature change in a calorimetry experiment, state two good practices to obtain an accurate result.", "(1) Use a polystyrene cup with a lid to reduce heat loss to the surroundings. (2) Stir the mixture continuously and record the maximum (or minimum) temperature quickly before heat is lost to the surroundings.", "Saying 'be careful' or not stirring the mixture.", "Insulation reduces heat loss; stirring ensures even temperature distribution; read the maximum/minimum temperature quickly."),

        // ================================================================
        // RATE OF REACTIONS (8 questions)
        // ================================================================
        q("rate_r1", .rate, .planning, 3, "Plan an experiment to investigate how the concentration of hydrochloric acid affects the rate of reaction with magnesium. State the variables and describe the procedure.", "IV: concentration of HCl (e.g. 0.5, 1.0, 1.5, 2.0, 2.5 mol/dm³). DV: volume of H₂ gas produced in 60 seconds (cm³). CVs: volume of HCl (25 cm³), mass of Mg (0.50 g), surface area of Mg, temperature, same apparatus. Procedure: measure 25 cm³ HCl into a conical flask connected to a gas syringe; add 0.50 g Mg ribbon; start timer immediately and insert stopper; record gas volume after 60 s; repeat with each concentration; repeat each twice and calculate the mean volume.", "Not controlling temperature or surface area, or not repeating the experiment.", "Only the independent variable should change; repeat for reliability and calculate a mean."),
        q("rate_r2", .rate, .ace, 2, "Explain why increasing the temperature of a reaction mixture usually increases the rate.", "At higher temperatures, particles have greater kinetic energy. They move faster, collide more frequently, and a greater proportion of collisions have energy equal to or above the activation energy. More successful collisions per unit time means a faster rate.", "Saying 'particles are bigger' or 'there are more particles'.", "Use collision theory: more frequent collisions AND a greater fraction have energy ≥ activation energy."),
        q("rate_r3", .rate, .pdo, 2, "A volume-of-gas vs time graph is steep at the start and becomes gradually less steep, eventually levelling off. What does this tell you about the rate?", "The rate is fastest at the start (steepest gradient) and decreases over time as reactants are used up. The graph levels off when the reaction is complete (a reactant is fully consumed).", "Saying the reaction stops immediately or that the rate is constant throughout.", "Gradient = rate for a volume-time graph; steeper gradient = faster rate."),
        q("rate_r4", .rate, .ace, 2, "In a reaction, 45 cm³ of CO₂ was produced in 30 seconds. Calculate the average rate in cm³/s.", "Rate = volume / time = 45 / 30 = 1.5 cm³/s.", "Forgetting units, or dividing time by volume.", "Rate = amount of product / time; always state units (cm³/s for gas volume, or s⁻¹ for the 1/time method)."),
        q("rate_r5", .rate, .mmo, 2, "In the sodium thiosulfate + HCl reaction, a cross drawn on paper beneath the flask disappears after a certain time. Explain how the rate is calculated from this method.", "Rate = 1 / time taken for the cross to disappear (s⁻¹). The shorter the time, the faster the rate. The sulfur precipitate clouds the solution, obscuring the cross.", "Using volume/time instead of 1/time for this method.", "Use 1/time only when measuring the time for a fixed event (cross disappearing); use volume/time when collecting gas over a period."),
        q("rate_r6", .rate, .ace, 2, "Explain why powdered calcium carbonate reacts faster with acid than large lumps of calcium carbonate.", "Powder has a larger surface area, so more particles are exposed and available for collisions at any time. This increases the frequency of effective collisions, increasing the rate.", "Saying powder has more calcium carbonate (it is the same mass, just a different surface area).", "Same mass but more surface area exposed → more frequent collisions → faster rate."),
        q("rate_r7", .rate, .ace, 3, "Using collision theory, explain how increasing the concentration of a reactant affects the rate of a reaction between two solutions.", "Increasing concentration means more reactant particles per unit volume. Particles collide more frequently, so the number of effective collisions per unit time increases. However, the activation energy is unchanged — each collision still needs sufficient energy. The increased frequency of successful collisions increases the rate.", "Saying concentration changes the activation energy.", "Concentration increases collision frequency, not the energy of individual collisions."),
        q("rate_r8", .rate, .pdo, 2, "Complete the following: In a rate experiment, the _____ variable is deliberately changed, the _____ variable is measured, and the _____ variables are kept constant.", "Independent variable is deliberately changed; dependent variable is measured; controlled variables are kept constant.", "Calling every measured quantity a controlled variable.", "State exactly what is changed (IV), measured (DV), and kept constant (CVs)."),

        // ================================================================
        // ORGANIC CHEMISTRY (8 questions)
        // ================================================================
        q("org_r1", .organic, .mmo, 2, "Describe the test for an alkene using aqueous bromine (bromine water) and state the observation.", "Add bromine water (orange/brown) to the sample and shake. If an alkene is present, the bromine water decolourises from orange/brown to colourless.", "Saying the bromine water changes to blue or green.", "Alkenes decolourise bromine water (orange → colourless) due to the C=C double bond (addition reaction)."),
        q("org_r2", .organic, .ace, 3, "Explain why cracking is important in the petrochemical industry.", "Cracking is the thermal decomposition of large hydrocarbon molecules into smaller, more useful molecules. It converts long-chain alkanes (less useful, lower demand) into shorter-chain alkanes (used as fuels) and alkenes (used as feedstock for polymers and other chemicals). This balances the supply and demand for different fractions from crude oil.", "Saying cracking is just burning crude oil, or that it produces only alkanes.", "Cracking produces both alkanes and alkenes; it increases the supply of useful smaller molecules from larger, less useful ones."),
        q("org_r3", .organic, .ace, 2, "State the products of the complete combustion of ethane (C₂H₆) and write the balanced equation.", "Complete combustion of ethane produces carbon dioxide and water. Equation: 2C₂H₆ + 7O₂ → 4CO₂ + 6H₂O.", "Saying carbon monoxide is produced (that is incomplete combustion).", "Complete combustion: sufficient O₂ → CO₂ + H₂O. Incomplete: insufficient O₂ → CO and/or C (soot)."),
        q("org_r4", .organic, .ace, 2, "Explain how to distinguish between ethane (C₂H₆) and ethene (C₂H₄) using a chemical test.", "Add bromine water to each. Ethene (an alkene, has a C=C double bond) decolourises bromine water from orange to colourless. Ethane (an alkane, saturated, no double bond) does not react — the bromine water stays orange.", "Saying both decolourise bromine water.", "Only alkenes decolourise bromine water; alkanes are saturated and do not react under these conditions."),
        q("org_r5", .organic, .pdo, 2, "Describe what happens during the addition polymerisation of ethene to form poly(ethene).", "Ethene monomers (each with a C=C double bond) join together. The double bond opens and the carbon atoms link to form a long chain. The repeating unit is −(−CH₂−CH₂−)−n. No small molecule is lost (addition polymerisation).", "Drawing the monomer with the double bond intact in the polymer, or showing a small molecule being eliminated.", "In addition polymerisation, the C=C double bond opens; the polymer chain has only single C−C bonds."),
        q("org_r6", .organic, .ace, 2, "Explain why the boiling points of alkanes increase as the chain length increases.", "As the number of carbon atoms increases, the molecules have larger surface areas and stronger intermolecular forces (van der Waals forces). More energy is needed to overcome these forces, so the boiling point increases.", "Saying the covalent bonds become stronger (it is intermolecular forces, not covalent bonds, that are overcome during boiling).", "Boiling involves overcoming intermolecular forces, not breaking covalent bonds within molecules."),
        q("org_r7", .organic, .planning, 3, "Describe the conditions needed for the fermentation of glucose to produce ethanol.", "Dissolve glucose in water in a conical flask. Add yeast. Seal with a delivery tube leading to limewater (to confirm CO₂ production). Keep at a warm temperature (about 35 °C) for several days in the absence of air. Yeast contains enzymes that catalyse: C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂.", "Using temperatures above 40 °C (enzymes denature) or not sealing the flask from air.", "Yeast enzymes work best around 35 °C; too hot denatures enzymes; too cold slows the reaction; air must be excluded."),
        q("org_r8", .organic, .ace, 3, "Ethene reacts with steam to form ethanol. State the conditions and write the equation. What type of reaction is this?", "Conditions: high temperature (about 300 °C), high pressure (about 60 atm), and a phosphoric acid catalyst (H₃PO₄). Equation: C₂H₄ + H₂O → C₂H₅OH. This is an addition reaction (the C=C double bond opens and H₂O adds across it).", "Saying it is a combustion or substitution reaction, or omitting the catalyst.", "Hydration of ethene: addition of steam across the C=C double bond, catalysed by phosphoric acid (H₃PO₄)."),

        // ================================================================
        // AIR QUALITY (7 questions)
        // ================================================================
        q("air_r1", .airQuality, .ace, 3, "Explain how sulfur dioxide (SO₂) contributes to acid rain and describe one environmental effect.", "SO₂ is released from burning fossil fuels containing sulfur impurities. In the atmosphere, SO₂ is oxidised and dissolves in rainwater to form sulfurous/sulfuric acid, which falls as acid rain. Effects: damages vegetation, acidifies lakes and rivers (harming aquatic life), and corrodes limestone buildings and statues.", "Saying SO₂ itself is an acid rain component without explaining the atmospheric oxidation and dissolution.", "SO₂ → oxidised in atmosphere → dissolves in water → acidic solution → acid rain with environmental damage."),
        q("air_r2", .airQuality, .ace, 2, "Give two methods to reduce carbon dioxide emissions from energy production.", "(1) Use renewable energy sources (solar, wind, hydroelectric) instead of fossil fuels. (2) Improve energy efficiency (better insulation, more efficient engines) to reduce the total fuel burned.", "Saying 'plant trees' as the only method (this removes CO₂ but does not reduce emissions at source).", "Separate reducing emissions (renewables, efficiency) from removing CO₂ already in the atmosphere (carbon capture, afforestation)."),
        q("air_r3", .airQuality, .mmo, 2, "A gas turns damp blue litmus paper red and then bleaches it. Identify the gas and state its colour.", "The gas is chlorine (Cl₂). It is a greenish-yellow gas. Chlorine is acidic (turns litmus red) and bleaches the litmus paper.", "Saying the gas is sulfur dioxide (which turns litmus red but does not bleach it).", "Cl₂: greenish-yellow, bleaches damp litmus. SO₂: colourless, turns acidified KMnO₄ colourless (does not bleach litmus)."),
        q("air_r4", .airQuality, .ace, 2, "Explain how a catalytic converter reduces pollutant emissions from car exhausts.", "A catalytic converter contains a transition metal catalyst (e.g. platinum/palladium/rhodium). It converts harmful exhaust gases: carbon monoxide (CO) is oxidised to CO₂, and nitrogen oxides (NOₓ) are reduced to N₂. This reduces the emission of toxic gases.", "Saying the catalytic converter filters or traps the gases.", "The catalyst converts CO → CO₂ (oxidation) and NOₓ → N₂ (reduction); it does not filter or trap gases."),
        q("air_r5", .airQuality, .planning, 3, "Plan a fair comparison of the amount of soot (carbon) produced when burning two different fuels.", "Burn equal masses of each fuel under the same conditions (same flame height, same apparatus). Hold a white ceramic tile or filter paper at the same height above each flame for the same time. Compare the darkness and amount of black deposit on the tile. Controlled variables: mass of fuel, height of tile, time of exposure, same tile material.", "Changing the mass of fuel or the height of the tile between the two tests.", "Control all variables except the fuel type; compare the blackness/mass of soot deposited on the tile."),
        q("air_r6", .airQuality, .ace, 2, "Explain how nitrogen oxides (NOₓ) are formed in car engines.", "In the high temperature of a car engine, nitrogen and oxygen from the air react to form nitrogen oxides (NO and NO₂). The high temperature provides enough energy for the normally unreactive N₂ to react with O₂.", "Saying nitrogen oxides come from the fuel (they come from the air, not the fuel).", "NOₓ forms from N₂ and O₂ in the air at high combustion temperatures, not from the fuel itself."),
        q("air_r7", .airQuality, .pdo, 2, "The table shows CO₂ levels increasing from 315 ppm (1960) to 420 ppm (2023). State the trend and suggest one consequence.", "CO₂ levels have increased by 105 ppm (from 315 to 420) over 63 years, showing a steady upward trend. One consequence: enhanced greenhouse effect leading to global warming, causing rising sea levels and climate change.", "Saying the levels have decreased or stayed the same.", "CO₂ is a greenhouse gas; rising levels correlate with increasing global temperatures and climate change."),

        // ================================================================
        // EXAM SKILLS: SALTS, AMMONIA, DATA, SAFETY, MEASUREMENT, GRAPH, PLANNING (7 questions)
        // ================================================================
        q("salt_r1", .salts, .planning, 3, "Plan how to prepare a pure, dry sample of sodium chloride from hydrochloric acid and sodium hydroxide solution.", "Use titration to find the exact reacting volumes: pipette 25.0 cm³ of NaOH into a conical flask, add methyl orange indicator, titrate with HCl until the colour changes. Repeat to find concordant titres. Then repeat the titration without indicator using the exact volumes found. Mix the measured volumes in an evaporating basin. Evaporate some water, then allow to crystallise. Filter the crystals and dry between sheets of filter paper.", "Adding excess acid or alkali when a pure soluble salt is needed, or not removing the indicator before crystallisation.", "Titration finds the stoichiometric volumes; repeat without indicator to avoid contaminating the salt with indicator."),
        q("ammonia_r1", .ammonia, .ace, 2, "State the raw materials and one set of industrial conditions used in the Haber process for manufacturing ammonia.", "Raw materials: nitrogen (from air) and hydrogen (from natural gas). Conditions: elevated temperature (about 450 °C), elevated pressure (about 200 atm), and an iron catalyst. The reaction is reversible: N₂ + 3H₂ ⇌ 2NH₃.", "Saying oxygen is a reactant, or that the reaction is irreversible.", "N₂ and H₂ only; iron catalyst; the reaction is reversible (⇌), so not all reactants are converted."),
        q("data_r1", .dataBased, .pdo, 2, "A student records four titres: 23.50, 23.20, 23.15, and 23.30 cm³. Which are concordant and what is the mean titre?", "Concordant titres: 23.20, 23.15, and 23.30 cm³ (all within 0.20 cm³ of each other; 23.50 is 0.35 cm³ from 23.15, so it is not concordant). Mean = (23.20 + 23.15 + 23.30)/3 = 23.22 cm³.", "Averaging all four titres or including the anomalous 23.50.", "Check that all selected titres are within 0.20 cm³ of each other before calculating the mean."),
        q("safety_r1", .safety, .planning, 2, "State two specific safety precautions when heating a hydrated salt in a boiling tube to determine its water of crystallisation.", "(1) Wear safety goggles to protect eyes from splashing or spitting of hot salt. (2) Hold the boiling tube at an angle and point the opening away from people to prevent hot solids escaping. Also heat gently to avoid decomposition of the salt.", "Saying 'be careful' without a specific action that reduces a stated risk.", "Specific precautions: goggles, angled tube, gentle heating — each addresses a specific identified risk."),
        q("meas_r1", .generalMeasurement, .mmo, 2, "A balance displays a reading of 2.50 g. How should this be recorded, and why?", "2.50 g. The balance displays to 0.01 g precision, so the reading should be recorded as 2.50 g (three significant figures) to preserve the precision of the instrument.", "Writing 2.5 g and losing a decimal place of precision.", "Do not discard justified trailing zeros; they indicate the precision of the measurement."),
        q("graph_r1", .generalGraph, .pdo, 2, "State three good practices when plotting a graph from experimental data.", "(1) Label both axes with the quantity and its unit. (2) Choose a scale that uses most of the grid with sensible equal intervals. (3) Plot points accurately with small crosses or dots, and draw a best-fit line (not dot-to-dot).", "Joining every point with straight lines, or not labelling units on the axes.", "Best-fit line shows the trend; axes must include units; use most of the grid for the scale."),
        q("plan_r1", .generalPlanning, .planning, 3, "For an investigation into the effect of temperature on reaction rate, state the independent, dependent, and two controlled variables.", "Independent variable: temperature (e.g. 20, 30, 40, 50, 60 °C). Dependent variable: time taken to collect a fixed volume of gas (e.g. 50 cm³) or volume of gas collected in a fixed time. Controlled variables: concentration and volume of reactants, mass/size of any solid reactant, same apparatus, same starting temperature of solutions.", "Not distinguishing between the three types of variables, or calling every measured quantity a controlled variable.", "IV = what you deliberately change; DV = what you measure; CVs = what you keep constant for a fair test.")
    ]
}

extension AceQuestionBank {
    static let realExpanded: [AceQuestion] = all + realExpandedQuestions
}
